name: publish image to docker hub

# The workflow is split into several sub jobs
# 1. prepare-tags: 
#    This step finds the latest mbed-os version (in terms of product version not date)
#    and generates a unique dev version for the image. 
#    The DEV docker tag takes the format of dev-<MBED_OS_VERSION>-<human readable date>-<UUID>
# 2. build-container:
#    The dev version of image is built here and pushed to docker hub.
#    When multiarch image is built docker buildx doesn't support exporting to docker
#    Hence, need to push to a registry (dockerhub).
# 3. test-container:
#    This tests the dev docker images
# 4. deploy-container
#    At this point, docker image marked as "dev" is ready to tag as "prod"
#    Also, deletes the dev tag
#    The dev images that didn't succeed is kept in docker hub for troubleshooting purposes.
#    Published docker tags are:
#    1. <MBED_OS_VERSION>-latest
#    2. <MBED_OS_VERSION>-<human readable date>
#    3. latest
#    This can be move with another workflow

on:

  # TODO: Enable when DockerHub Storage policy is understood
  # schedule:
  #   - cron:  '15 4 * * *'
    
  push:
    branches: [ master, mbed-os-env ]


  workflow_dispatch:

jobs:
  prepare-tags:
    runs-on: ubuntu-latest


    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
          depth: 0

      # - run: git fetch --prune --unshallow

      - 
        name: Find the latest release mbed-os version
        id: mbed_os_version
        shell: bash
        run: |
          value=`git describe --tags --abbrev=0  --match mbed-os-*.[0-9]`
          echo "TAG is $value"
          echo "::set-output name=tag::$value"

      - 
        name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1

# set docker tags we are building, and intending to publish
# dev-tag is temporary for testing purpose. This should be considered as unstable.
# dated-tag is created for versioning purpose
# prod-tag-latest could be used by customers, CI etc for keeping up to date
      - 
        name: Get build information
        shell: bash
        run: |
          mkdir -p build_info
          date=$(date +"%Y.%m.%dT%H.%M.%S")
          echo dev-${{ steps.mbed_os_version.outputs.tag }}-${date}-${{ steps.generate-uuid.outputs.uuid }} > build_info/dev_tag
          echo ${{ steps.mbed_os_version.outputs.tag }}-${date} > build_info/prod_tag_dated
          echo ${{ steps.mbed_os_version.outputs.tag }}-latest > build_info/prod_tag_latest
          echo ${{ steps.mbed_os_version.outputs.tag }} > build_info/mbed_os_version

      # archiving and unarchiving are github actions ways to pass variables between jobs    
      - 
        name: Archive information 
        uses: actions/upload-artifact@v2
        with:
          name: build-info
          path: build_info
          

  build-container:
    runs-on: ubuntu-latest
    needs: prepare-tags

    steps:
      - 
        name: unarchive artefacts
        uses: actions/download-artifact@v2
        with:
          name: build-info
          
      - 
        name: Get build info from archive
        shell: bash
        id: build_info
        run: |
          value=`cat dev_tag`
          echo "TAG is $value"
          echo "::set-output name=DOCKER_DEV_TAG::$value"
          value=`cat prod_tag_dated`
          echo "TAG is $value"
          echo "::set-output name=DOCKER_PROD_TAG_DATED::$value"
          value=`cat prod_tag_latest`
          echo "::set-output name=DOCKER_PROD_TAG_LATEST::$value"

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          # username: ${{ github.actor }}
          # password: ${{ secrets.DOCKERHUB_PASSWORD }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # username: ${{ github.repository_owner }}
          # password: ${{ secrets.GITHUB_TOKEN }}

      # - 
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     # username: ${{ github.actor }}
      #     # password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #     registry: docker.pkg.github.com
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     # username: ${{ github.repository_owner }}
      #     # password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Build with remote cache
        uses: docker/build-push-action@v2
        id: docker_build_dev
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          # platforms: linux/amd64
          # load: true - not supported for multi arch
          push: true
          file: ./docker_images/mbed-os-env/Dockerfile
          tags: ghcr.io/${{ github.actor }}/mbed-os-env-tmp:${{ steps.build_info.outputs.DOCKER_DEV_TAG }}
          # tags: docker.pkg.github.com/${{ github.repository_owner }}/mbed-os/mbed-os-env:${{ steps.build_info.outputs.DOCKER_DEV_TAG }}
          cache-from: type=registry,ref=ghcr.io/${{ github.actor }}/mbed-os-env-tmp:latest
          cache-to: type=inline

    
      # -
      #   name: Build with remote cache
      #   uses: docker/build-push-action@v2
      #   id: docker_build_dev
      #   with:
      #     context: .
      #     # platforms: linux/amd64,linux/arm64
      #     platforms: linux/amd64
      #     push: true
      #     file: ./docker_images/mbed-os-env/Dockerfile
      #     tags: docker.pkg.github.com/${{ github.repository }}/mbed-os-env:${{ steps.build_info.outputs.DOCKER_DEV_TAG }}
      #     # tags: docker.pkg.github.com/${{ github.repository_owner }}/mbed-os/mbed-os-env:${{ steps.build_info.outputs.DOCKER_DEV_TAG }}
      #     # cache-from: type=registry,ref=${{ github.actor }}/mbed-os-env:latest
      #     cache-to: type=inline


  test-container:
    runs-on: ubuntu-latest
    needs: build-container
    outputs:
      STATUS: ${{ steps.test.outputs.STATUS }}
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        # platform: [linux/amd64]
        
    steps:
      - 
        name: unarchive artefacts
        uses: actions/download-artifact@v2
        with:
          name: build-info
          
      - 
        name: Get build info from archive
        shell: bash
        id: build_info
        run: |
          value=`cat dev_tag`
          echo "TAG is $value"
          echo "::set-output name=DOCKER_DEV_TAG::$value"
          value=`cat prod_tag_dated`
          echo "TAG is $value"
          echo "::set-output name=DOCKER_PROD_TAG_DATED::$value"
          value=`cat prod_tag_latest`
          echo "::set-output name=DOCKER_PROD_TAG_LATEST::$value"
          value=`cat mbed_os_version`
          echo "::set-output name=MBED_OS_VERSION::$value"

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - 
        name: Checkout
        uses: actions/checkout@v2
            
      - 
        name: Find DOCKER DIGEST trying to publish (if exists in docker hub)
        id: docker_info_prod
        run: |
          DIGEST=$(python ./.github/workflows/ci_scripts/docker_hub_utils.py -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} get-digest -r mbed-os-env -t ${{ steps.build_info.outputs.DOCKER_PROD_TAG_LATEST }} -p ${{ matrix.platform }} )
          echo "::set-output name=DIGEST::$DIGEST"
          echo "Docker DIGEST: $DIGEST"

      - 
        name: Find DEV DOCKER DIGEST
        id: docker_info_dev
        run: |
          DIGEST=$(python ./.github/workflows/ci_scripts/docker_hub_utils.py -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} get-digest -r mbed-os-env-tmp -t ${{ steps.build_info.outputs.DOCKER_DEV_TAG }} -p ${{ matrix.platform }} )
          echo "::set-output name=DIGEST::$DIGEST"
          echo "Docker DIGEST: $DIGEST"

      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # no need to test (nor publish) if we already have the same image in dockerhub
      - if: steps.docker_info_prod.outputs.DIGEST != steps.docker_info_dev.outputs.DIGEST
        name: test the container
        id: test
        uses: addnab/docker-run-action@v2
        with:
          options: -v ${{ github.workspace }}:/work -w=/work
          image: ghcr.io/${{ github.actor }}/mbed-os-env-tmp@${{ steps.docker_info_dev.outputs.DIGEST }}
          shell: bash
          run: |
            set -e
            echo "::set-output name=STATUS::failed"
            uname -m
            ./docker_images/mbed-os-env/test.sh ${{ steps.build_info.outputs.MBED_OS_VERSION }}
            echo "::set-output name=STATUS::passed"
            
      
  deploy-container:
    runs-on: ubuntu-latest
    needs: test-container
    if:  ${{ always() }}
        
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - 
        name: unarchive artefacts
        uses: actions/download-artifact@v2
        with:
          name: build-info
        
      - 
        name: Get build info from archive
        shell: bash
        id: build_info
        run: |
          value=`cat dev_tag`
          echo "TAG is $value"
          echo "::set-output name=DOCKER_DEV_TAG::$value"
          value=`cat prod_tag_dated`
          echo "TAG is $value"
          echo "::set-output name=DOCKER_PROD_TAG_DATED::$value"
          value=`cat prod_tag_latest`
          echo "::set-output name=DOCKER_PROD_TAG_LATEST::$value"
          
      - 
        # if: needs.test-container.outputs.STATUS == 'passed'
        name: copy dev tag to prod
        run: |
          docker run quay.io/skopeo/stable --src-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} --dest-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} copy --all docker://ghcr.io/${{ github.actor }}/mbed-os-env-tmp:${{ steps.build_info.outputs.DOCKER_DEV_TAG }}  docker://ghcr.io/${{ github.actor }}/mbed-os-env:${{ steps.build_info.outputs.DOCKER_PROD_TAG_LATEST }}
          docker run quay.io/skopeo/stable --src-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} --dest-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} copy --all docker://ghcr.io/${{ github.actor }}/mbed-os-env-tmp:${{ steps.build_info.outputs.DOCKER_DEV_TAG }}  docker://ghcr.io/${{ github.actor }}/mbed-os-env:${{ steps.build_info.outputs.DOCKER_PROD_TAG_DATED }}
          docker run quay.io/skopeo/stable --src-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} --dest-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} copy --all docker://ghcr.io/${{ github.actor }}/mbed-os-env-tmp:${{ steps.build_info.outputs.DOCKER_DEV_TAG }}  docker://ghcr.io/${{ github.actor }}/mbed-os-env:latest
      
      - if: needs.test-container.outputs.STATUS == 'failed'
        name: Rename Dev Tag
        run: |
          docker run quay.io/skopeo/stable --src-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} --dest-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} copy --all docker://ghcr.io/${{ github.actor }}/mbed-os-env-tmp:${{ steps.build_info.outputs.DOCKER_DEV_TAG }}  docker://ghcr.io/${{ github.actor }}/mbed-os-env-tmp:failed-${{ steps.build_info.outputs.DOCKER_DEV_TAG }}

      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        with:
          # NOTE: at now only orgs is supported
          owner: ${{ github.actor }}
          name: ghcr.io/${{ github.actor }}/mbed-os-env-tmp
          # NOTE: using Personal Access Token
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.build_info.outputs.DOCKER_DEV_TAG }}

      # - 
      #   name: Delete Dev Tag
      #   run: |
      #     python ./.github/workflows/ci_scripts/docker_hub_utils.py -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} delete-tag -r mbed-os-env -t ${{ steps.build_info.outputs.DOCKER_DEV_TAG }}
