on:
  workflow_run:
    workflows: ["Publish new dev version of docker image"]
    branches: [master]
    types: 
      - completed

jobs:
  build-container:
    runs-on: ubuntu-latest
    # needs: prepare-tags
    # outputs:
    #   DEV_DIGEST: ${{ steps.docker_info_dev.outputs.DIGEST }}
    #   PROD_DIGEST: ${{ steps.docker_info_prod.outputs.DIGEST }}

    steps:
      - 
        name: unarchive artefacts
        uses: actions/download-artifact@v2
        with:
          name: build-info