name: Prune temporary docker images

on:    
  schedule:
    - cron:  '15 4 * * *'

  workflow_dispatch:

jobs:
  prune-images:
    if: github.repository_owner == 'saheerb'
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - 
        name: Delete old temporary images
        run: |
          python ./.github/workflows/ci_scripts/github_utils.py -u ${{ github.actor }} -p ${{ secrets.ANOTHER_GITHUB_TOKEN }} delete-old-images -r mbed-os-env-tmp
          