name: Release or update docker image for a released mbed-os version

# Design doc: https://github.com/ARMmbed/mbed-os/blob/master/docs/design-documents/docker_management

# This work flow is disabled for forked repositories. 
# If you need to enable it, find references for github.repository_owner in this file
# and replace with ARMmbed with your organisation/account name

on:
  pull_request:
    branches: [ master ]

jobs:
  # this job finds the necessary tags to be applied to docker image
  prepare-tags:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2

      - 
        name: Hack
        run: |
          python .github/workflows/ci_scripts/github_utils.py -u ${{ github.actor }} -p ${{ secrets.DOCKER_MANAGEMENT_TOKEN }}
          python .github/workflows/ci_scripts/github_utils.py -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          
