name: Build and test image when PR is raised

# This workflow is triggered when Dockerfile relatedt or github action itself changes are made in a PR
# The workflow is quite simple - builds and test the image. Release of newer version is done only when PR is merged.

on:
  pull_request:
    branches: [ master ]
    paths:
      - docker_images/mbed-os-env/**
      - .github/workflows/docker_management.*
      - requirements.txt

jobs:

  build-container:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      -
        name: Checkout
        uses: actions/checkout@v2
        
      
      # cache documentation: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
      -
        name: Build with remote cache
        uses: docker/build-push-action@v2
        id: docker_build_dev
        with:
          context: .
          platforms: ${{ matrix.platform }}
          file: ./docker_images/mbed-os-env/Dockerfile
          load: true
          tags: mbed-os-env:a_pr_test
          cache-from: type=registry,ref=ghcr.io/${{ github.actor }}/mbed-os-env:master-latest


      - 
        name: test the container
        id: test
        uses: addnab/docker-run-action@v2
        with:
          options: -v ${{ github.workspace }}:/work -w=/work
          image: mbed-os-env:a_pr_test
          shell: bash
          run: |
            set -e
            uname -m
            ./docker_images/mbed-os-env/test.sh 
