name: Publish or Update docker image for head of branch
# This work flow is disabled for forked repositories. 
# If you need to enable it, find references for github.repository_owner in this file
# and replace with ARMmbed with your organisation/account name
# Read more details in TODO: add design link

on:
  push:
    branches: 
      - master

    paths:
      - requirements.txt
      - docker_images/mbed-os-env/**
      - .github/workflows/docker_management.branch.yml

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    step:
      - 
        name: build information
        shell: bash
        id: build_info
        run: |
          date=$(date +"%Y.%m.%dT%H.%M.%S")
          branch_name=${GITHUB_REF#refs/heads/}
          echo "::set-output name=DOCKER_PROD_TAG_LATEST::${branch_name}-latest"
          echo "::set-output name=DOCKER_PROD_TAG_LATEST::${branch_name}-${date}"

      - 
        name: copy dev tag to prod
        run: |
          docker run quay.io/skopeo/stable --src-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} --dest-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} copy --all docker://ghcr.io/${{ github.actor }}/mbed-os-env-tmp:${{ github.sha }}  docker://ghcr.io/${{ github.actor }}/mbed-os-env:${{ steps.build_info.outputs.DOCKER_PROD_TAG_LATEST }}
          docker run quay.io/skopeo/stable --src-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} --dest-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} copy --all docker://ghcr.io/${{ github.actor }}/mbed-os-env-tmp:${{ github.sha }}  docker://ghcr.io/${{ github.actor }}/mbed-os-env:${{ steps.build_info.outputs.DOCKER_PROD_TAG_DATED }}
